auth:
  url: http://localhost:8888/authService/authRequest

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/library

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true