auth:
  url: http://host:8888/authService/authRequest

spring:
  data:
    mongodb:
      uri: mongodb://sboot_usr:1234@ds033986.mlab.com:33986/heroku_f9wknxrf

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true